# Generated by Django 5.2.2 on 2025-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.TextField(blank=True, max_length=100)),
                ('phonenumber', models.IntegerField(blank=True)),
            ],
        ),
    ]
